baseURL = "https://help.coopcycle.org/"
theme = "coopcycle"

DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[blackfriday]
extensions = ["hardLineBreak"]

[Taxonomies]

[Languages]

[Languages.en]
title = "CoopCycle - Help"

[Languages.fr]
title = "CoopCycle - Aide"
